development:
  encoding: utf8
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  encoding: utf8
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  encoding: utf8
  adapter: mysql2
  database: iemifi
  host: localhost
  username: root
  #password:

